Feature/user interface
JohnHernCode/tic-tac-toe pull request #2
Opened 2021-01-14 18:59 UTC by GuNner-pete

Assigning players' names and telling players to make their next moves

2021-01-14 19:37 UTC, GzimAsani requested changes
### CHANGES REQUIRED  :stop_sign: 
### HELLO **TEAM** You did a great job so far  :+1: but unfortunately your code breaks on line 5:
- [x]  The code breaks in  bin/main.rb:5:in `initialize': wrong number of arguments (given 0, expected 2) (ArgumentError), kindly fix this
### Also:
- [x] game tells which player turn it is (without computing who the winner is)
- [x] game informs player if the selected move is invalid (without computing what an invalid move is)
- [x] game informs player if the selected move is a winning move (without computing the winning move)
- [x] game informs player if the selected move is a draw move (without computing draw)
- [x] game repeats all actions for the next player's move
- [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))

### **Please make the required changes and submit another review request when you are ready.**

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

2021-01-14 19:37 UTC, GzimAsani commented on bin/main.rb
> +  def initialize(name, movement)
_Kindly fix this_
bin/main.rb:5:in `initialize': wrong number of arguments (given 0, expected 2) (ArgumentError)

2021-01-15 23:33 UTC, BrianSammit commented on bin/main.rb
> +  puts "Ready to play #{player1.name} and #{player2.name}? Let's go!"
I can't see this puts on the terminal, it just skips to the game. 

![CavernousEnergeticBluetonguelizard-size_restricted](https://user-images.githubusercontent.com/64173189/104788291-f93d8400-575f-11eb-8b5a-77768eb3dccc.gif)

2021-01-15 23:36 UTC, BrianSammit approved these changes
STATUS: Approve :muscle: 
HELLO TEAM!! :wave:  Excellent job working on the changes, the project is working amazing :smiley: 
---------------------------------------------------------------

- [ ] [OPTIONAL] fix the last two lines when the game starts. See my comments below.

--------------------------------------------------------

You can merge this milestone :clap: 

HAPPY CODING!!! Good luck with the next milestones. 

![MB5W4D](https://user-images.githubusercontent.com/64173189/104788563-81238e00-5760-11eb-989b-53c461fd404c.gif)

2021-01-15 23:41 UTC, merged